name: Run Pytest

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        sudo apt install portaudio19-dev
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel
        pip install -r requirements/webapp.txt
        pip install pytest

    - name: Create settings.py
      run: touch api/settings.py

    - name: Run tests
      run: |
        pytest
